name: bioe394e-env

channels:
  - conda-forge
  - defaults

dependencies:
  - datashader
  - gh
  - git
  - holoviews
  - ipywidgets
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-lsp
  - nbgitpuller
  - numba
  - panel
  - pip
  - pip:
    - -r requirements.txt
  - python
  - python-language-server
