name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - pytorch
  - torchvision
  - imageio
  - pip:
    - -r requirements.txt
    - nbgitpuller
    - nbviewer
