name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - scipy
  - dask
  - bokeh
  - pandas
  - scikit-learn
  - imageio
  - gh
  - git
  - holoviews
  - hvplot
  - ipywidgets
  - nbgitpuller
  - nbviewer
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-lsp
  - pip:
    - -r requirements.txt
  - pyarrow
  - python
  - python-language-server
  - pyviz_comms
  - torch
  - torchvision
