name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - scipy
  - dask
  - bokeh
  - pandas
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit
  - imageio
  - gh
  - git
  - holoviews
  - hvplot
  - ipywidgets
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-lsp
  - pip:
    - -r requirements.txt
    - nbgitpuller
    - nbviewer
